<?php

namespace App\Http\Controllers;

use App\Entities\DniType;
use Illuminate\Http\Request;
use App\Http\Repositories\ClientsRepo as Repo;
use Illuminate\Routing\Route;

class ClientsController extends Controller
{

    protected $repo;
    protected $module;
    protected $route;

    public function __construct(Repo $repo, Route $route)
    {
        $this->repo = $repo;
        $this->route = $route;
        $confFile = 'clients';

        // nombre de archivo de configuracion

        $this->confFile = $confFile;
        $this->data['confFile'] = $confFile;

    }



    public function create()
    {
        $this->data['provinces'] = ["Capital Federal", "Buenos Aires", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago Del Estero", "Tierra Del Fuego", "Tucuman"];
        $this->data['dniTypes'] = DniType::all()->pluck('type', 'id');

        return parent::create(); // TODO: Change the autogenerated stub
    }

    public function edit()
    {
        $this->data['provinces'] = ["Capital Federal", "Buenos Aires", "Catamarca", "Chaco", "Chubut", "Córdoba", "Corrientes", "Entre Ríos", "Formosa", "Jujuy", "La Pampa", "La Rioja", "Mendoza", "Misiones", "Neuquén", "Río Negro", "Salta", "San Juan", "San Luis", "Santa Cruz", "Santa Fe", "Santiago Del Estero", "Tierra Del Fuego", "Tucuman"];
        $this->data['dniTypes'] = DniType::all()->pluck('type', 'id');

        return parent::edit(); // TODO: Change the autogenerated stub
    }

}
