<?php

namespace App\Http\Controllers;

use App\Entities\AccreditationType;
use App\Entities\Client;
use App\Entities\DniType;
use App\Entities\Financing;
use App\Http\Repositories\ClientsRepo;
use Illuminate\Http\Request;
use Illuminate\Routing\Route;

class FormsController extends Controller
{

    protected $repo;
    protected $module;
    protected $route;
    protected $clientsRepo;

    public function __construct( Route $route, Request $request, ClientsRepo $clientsRepo)
    {
        $this->route = $route;
        $confFile = 'forms';

        $this->clientsRepo = $clientsRepo;

        // nombre de archivo de configuracion
        $this->confFile = $confFile;
        $this->data['confFile'] = $confFile;

        $this->request = $request;
        $this->route = $route;
    }

    public function index()
    {
        return view(config($this->confFile.".viewIndex"))->with($this->data);
    }


    public function create()
    {
        $this->data['clients'] = $this->clientsRepo->getClientList();
        $this->data['provinces'] = ["Capital Federal","Buenos Aires","Catamarca","Chaco","Chubut","Córdoba","Corrientes","Entre Ríos","Formosa","Jujuy","La Pampa","La Rioja","Mendoza","Misiones","Neuquén","Río Negro","Salta","San Juan","San Luis","Santa Cruz","Santa Fe","Santiago Del Estero","Tierra Del Fuego","Tucuman"];
        $this->data['dniTypes'] = DniType::all()->pluck('type','id');
        $this->data['accreditationsType'] = AccreditationType::all()->pluck('type','id');
        $this->data['financing'] = Financing::all();

        return parent::create(); // TODO: Change the autogenerated stub
    }
}
